### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 117: character maps to <undefined>

### ISSUE THREAD

**Issue by tickwei** [mesolitica/malaya#160]
### Error when running this code:
import malaya
model = malaya.sentiment.transformer(model = 'xlnet')

### Log:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\herpetologist\__init__.py", line 100, in check
    return func(*args, **kwargs)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\malaya\sentiment.py", line 112, in transformer
    return classification.transformer(
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\malaya\supervised\classification.py", line 189, in transformer
    tokenizer = TOKENIZER_MODEL[model](vocab_file=path['vocab'], spm_model_file=path['tokenizer'])
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\malaya\text\bpe.py", line 89, in __init__
    v = fopen.read().split("\n")[:-1]
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 117: character maps to <undefined>

**Comment by tickwei** [comment]
### solution:
"C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\malaya\text\bpe.py", line 89
Specify the encoding when opening the file:
with open(vocab_file, encoding="utf8") as fopen:

**Comment by huseinzol05** [comment]
https://malaya.readthedocs.io/en/stable/running-on-windows.html
